# Generated by Django 3.1.1 on 2020-09-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Unique Car Identifier')),
                ('make', models.CharField(max_length=100, unique=True, verbose_name='Make/Brand of the car')),
                ('model', models.CharField(max_length=100, verbose_name='Model name of the car')),
                ('year', models.IntegerField(verbose_name='Year of car model')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Unique Issue Identifier')),
                ('name', models.CharField(max_length=100, verbose_name='Issue Name')),
                ('description', models.CharField(max_length=3000, verbose_name='Description of the issue')),
                ('recall', models.BooleanField(verbose_name='Recall Status')),
                ('notification', models.BooleanField(verbose_name='Notification Status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Unique User Identifier')),
                ('name', models.CharField(max_length=100, verbose_name="User's First & Last Name")),
                ('mobile', models.IntegerField(blank=True, unique=True, verbose_name="User's mobile number")),
                ('email', models.CharField(max_length=100, unique=True, verbose_name="User's email address")),
                ('country', models.CharField(max_length=100, verbose_name="User's country")),
                ('postcode', models.IntegerField(verbose_name="User's postcode")),
                ('cars', models.ManyToManyField(blank=True, to='checkyourcar.Car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='issues',
            field=models.ManyToManyField(blank=True, to='checkyourcar.Issue'),
        ),
    ]
