# Generated by Django 3.1.1 on 2020-09-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkyourcar', '0002_auto_20200909_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='First & Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.IntegerField(verbose_name='Postcode'),
        ),
    ]
