# Generated by Django 3.0.1 on 2020-09-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkyourcar', '0005_auto_20200925_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Identifier'),
        ),
    ]
