# Generated by Django 3.0.1 on 2020-09-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkyourcar', '0006_auto_20200925_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cars',
            field=models.ManyToManyField(blank=True, to='checkyourcar.Car'),
        ),
    ]
