# Generated by Django 3.0.1 on 2020-09-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkyourcar', '0007_issue_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='cars',
        ),
    ]
