# Generated by Django 3.0.1 on 2020-09-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkyourcar', '0009_car_auth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='auth_user',
            new_name='users',
        ),
    ]
