# Generated by Django 3.1.1 on 2020-09-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkyourcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Make/Brand of the car'),
        ),
    ]
