# Generated by Django 3.0.1 on 2020-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkyourcar', '0004_carissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Identifier'),
        ),
        migrations.DeleteModel(
            name='CarIssue',
        ),
    ]
