# Generated by Django 3.0.1 on 2020-09-26 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkyourcar', '0008_remove_issue_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='auth_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
