# Generated by Django 3.0.1 on 2020-09-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkyourcar', '0010_auto_20200926_0358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
